### ISSUE TITLE
Ansible Scaffold

### ISSUE THREAD

**Issue by yg-ht** [nettitude/PoshC2#102]
Hey,
Please could you include an Ansible scaffold in your repo?
Thanks!

**Comment by yg-ht** [comment]
(I am writing one at the moment, so I will send a Pull req if I get there first, but you probably can spin one up much quicker)

**Comment by riskydissonance** [comment]
I'll take a look but not used Ansible, any PR or input even as a starting point would be 👌

**Comment by yg-ht** [comment]
Well so far I have the following for deploying a new Posh server (tested on Ubuntu 18.04):

[ansible-poshc2-deploy-main.yml.txt](https://github.com/nettitude/PoshC2/files/4535375/ansible-poshc2-deploy-main.yml.txt)

Which will get you started.  This is the main.yml file from the tasks directory of an Ansible role.  It would be great to get a similar deployment script for redirector deployment, and then it would also be awesome if you could glue things together automatically as well, but that is starting to get a bit advanced.

**Comment by riskydissonance** [comment]
Awesome thanks, we'll take a look !

**Comment by riskydissonance** [comment]
Hey, added a PR and tagged you: https://github.com/nettitude/PoshC2/pull/141

**Comment by riskydissonance** [comment]
Closing issues as PR opened, any further comments to go there
