### ISSUE TITLE
Cannot find module, loadmodule is case sensitive!

### ISSUE THREAD

**Issue by Cyb3rWard0g** [nettitude/PoshC2#103]
good evening PoshC2 team,

I m running custom modules and for some reason some of them can be loaded and some of them cannot :( . I added my modules to the /opt/PoshC2/resources/modules folder and I am using Docker btw.

My modules are in the right folder. Look at the last modules on the right

<img width="1377" alt="image" src="https://user-images.githubusercontent.com/9653181/80567309-d517f800-89c2-11ea-8ac0-4dc71f1b8527.png">

Some of them work but some do not. I get the following error:

```
Task 00076 (wardog) issued against implant 6 on host DMEVALS\SYSTEM* @ UTICA (29/04/2020 06:22:17)
loadmodule m

Cannot find module, loadmodule is case sensitive!
'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte
```

I do not know why it is showing `loadmodule m` . Once again it only happens with a few modules.  I am running APT29 ATT&CK Day 2 emulation plan and I am using these modules : https://github.com/mitre-attack/attack-arsenal/tree/master/adversary_emulation/APT29/Emulation_Plan/Day%202/payloads

One of the ones that does not run is the Invoke-Mimikatz for example. or the stepFourteen_credDump.ps1 one or timestomp.ps1 . Do you guys think how I can troubleshoot this issue? Files are in the right folder.

Thank you in advance!

**Comment by Cyb3rWard0g** [comment]
oh and that error kills my call back :( . I have defender off too 
<img width="891" alt="image" src="https://user-images.githubusercontent.com/9653181/80567589-7c952a80-89c3-11ea-91c2-9369af1e11a7.png">

**Comment by Cyb3rWard0g** [comment]
If run `listmodules`

```
DMEVALS\SYSTEM* @ UTICA (PID:2700)
PS 11> listmodules                                                                                                                                                                

[+] Available modules:
...
....
stepFifteen_wmi.ps1
stepFourteen_bypassUAC.ps1
stepFourteen_credDump.ps1
stepSeventeen_email.ps1
stepSeventeen_zip.ps1
stepSixteen_SID.ps1
stepThirteen.ps1
stepTwelve.ps1
....
.....
timestomp.ps1
wipe.ps1
....
```
I can see several of the custom modules there.

**Comment by riskydissonance** [comment]
Hey @Cyb3rWard0g, it looks like it might be an encoding issue, can you provide a specific example of a module that isn't working and the actual command you're running to load the module?

**Comment by Cyb3rWard0g** [comment]
Hey @m0rv4i , Yeah this is one example: https://github.com/mitre-attack/attack-arsenal/blob/master/adversary_emulation/APT29/Emulation_Plan/Day%202/payloads/Invoke-WinRMSession.ps1 . Looking a the error message, it looks like it is trying to load `m` right? Even though I type `loadmodule Invoke-WinRMSession.ps1` ,I get 

```
Task 00076 (wardog) issued against implant 6 on host DMEVALS\SYSTEM* @ UTICA (29/04/2020 06:22:17)
loadmodule m

Cannot find module, loadmodule is case sensitive!
'utf-8' codec can't decode byte 0x90 in position 2: invalid start byte
```

in my **resources/modules** folder I have a file which is a binary named `m`. Do you think it tries to load that instead? I just copied  most of the files from here: https://github.com/mitre-attack/attack-arsenal/tree/master/adversary_emulation/APT29/Emulation_Plan/Day%202/payloads to execute an emulation plan provided by ATT&CK, and `m` is there, but I never explicitly call it. I will remove that `m` and see if that fixes the issue.

**Comment by riskydissonance** [comment]
So I've `curl`'d down that file and it loads fine for me on latest version:

```
# file Invoke-WinRMSession.ps1
Invoke-WinRMSession.ps1: ASCII text
```
and
```
Task 00002 (user) issued against implant 1 on host DOMAIN\user1 @ WIN7-CLIENT1 (30/04/2020 08:59:16)
loadmodule Invoke-WinRMSession.ps1

Task 00002 (user) returned against implant 1 on host DOMAIN\user1 @ WIN7-CLIENT1 (30/04/2020 08:59:19)
Module loaded successfully
```
It still looks like an encoding issue, are you able to:
a) update to the latest version of PoshC2
b) check if the file is in ASCII or UTF-8 and covert it if it is not?

**Comment by Cyb3rWard0g** [comment]
Ok I will try it right now and let you know :) Thank you @m0rv4i ! :)

**Comment by Cyb3rWard0g** [comment]
OK it all works fine now. The issue was that I had this file https://github.com/mitre-attack/attack-arsenal/blob/master/adversary_emulation/APT29/Emulation_Plan/Day%202/payloads/m in the modules folder. I removed it and it worked fine. Thats why I was getting `Task 00076 (wardog) issued against implant 6 on host DMEVALS\SYSTEM* @ UTICA (29/04/2020 06:22:17)
loadmodule m` even though I was NOT loading that file.

**Comment by riskydissonance** [comment]
An no I see the problem, when we search for modules we're checking if the file name 'contains' the module name (so you can `loadmodule powerview` and it load powerview.ps1), however as the name 'm' is present in a lot of words that would be causing the problem. I'll look at changing the logic for that.

**Comment by riskydissonance** [comment]
Fixed this on the `dev` branch if you're able/want to test it

**Comment by riskydissonance** [comment]
Merged to `master`, any further issues let me know :)

**Comment by Cyb3rWard0g** [comment]
Thank you @m0rv4i . I appreciate it!
