### ISSUE TITLE
Question: ICMPv6

### ISSUE THREAD

**Issue by kotowarinone** [nettitude/PoshC2#108]
May I ask a question?
Does PoshC2 suite have a module which continuously observe ICMPv6 packets and output neighbor hosts activities?

**Comment by riskydissonance** [comment]
I don't believe so, but we have a lot of modules now.

PoshC2 can run .NET Assemblies, PowerShell modules and Python scripts in memory in the respective implants however, so if you find one or write one you should be able to just add it to the `resources/modules` directory and run it in the same way as any other module for that implant type.

Any pull requests for new tools are welcome :)

**Comment by kotowarinone** [comment]
I am very grateful for your kindness!
Thank you very much!
