### ISSUE TITLE
[BUG] Cannot upload file to target machine

### ISSUE THREAD

**Issue by JackHarboraa** [nettitude/PoshC2#109]
I am trying to upload a file onto a target machine.
When using the **upload-file** command, I get an error in the server log.

the handler input looks like this:
```
Location file to upload: nc.exe                                                                                   
Location to upload to: C:\\users\\admin\\Documents                                                                
Uploading /opt/PoshC2_Project/payloads/nc.exe to C:\\users\\admin\\Documents
```

The output of server log:
`ErrorUpload: The term 'Upload-File' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.`

**Comment by riskydissonance** [comment]
Hi,

It looks like **Stage2-Core.ps1** isn't loaded, can you try manually loading that module? Is it caught by AV etc?

If that doesn't work, please can you fill in the following?

## Execution Environment:
**All of this must be filled in**
Data | Value
------ | ------
Full Posh version (all the text between the === at the top of the Implant Handler) | <version data here>
OS & version | <os data here>
Using Docker/containerisation? | <container data here>

## Implant Info
* What implant does it occur on? PowerShell/C#/Python

## Defensive Technologies
* Is the target environment running any particular defensive products? AVs/EDRs etc?

**Comment by JackHarboraa** [comment]
**Stage2-Core.ps1** was not loading.  I loaded it manually and fixed the problem. Thanks!
