### ISSUE TITLE
[HELP] - Cannot make it work

### ISSUE THREAD

**Issue by b4b857f6ee** [nettitude/PoshC2#113]
## Description

My configuration isn't working, i can't get the payload remote access nothing work :/

## Execution Environment:
**All of this must be filled in**
Ubuntu 18.04 update and VM
------ | ------
Full Posh version (all the text between the === at the top of the Implant Handler) | v6.0
OS & version | Ubuntu 18.04

## Implant Info
* What implant does the problem occur on? All
* How was the implant created? Running a default payload

## Defensive Technologies
* Nothing

## To Reproduce 
Juste install by cloning the github
And try to make it work with Apache 2.

## Expected behavior
Remote access with the payload

## Screenshots
My local system is in 10.0.0.5 
for the Posh, 10.0.0.11 for the Apache 
and the client is 192.168.108.4

This is the Apache configuration
![image](https://user-images.githubusercontent.com/36012515/85315391-46ec5980-b4bb-11ea-8352-0875e9889698.png)

The redirection looks like to work because i have this : 
![image](https://user-images.githubusercontent.com/36012515/85315450-61bece00-b4bb-11ea-9fe4-f30a71affa84.png)

And this is my posh-config

![image](https://user-images.githubusercontent.com/36012515/85315492-71d6ad80-b4bb-11ea-9ee3-7d7e5eb4ec4a.png)

And the whitelist file
![image](https://user-images.githubusercontent.com/36012515/85315587-a0ed1f00-b4bb-11ea-8879-fec8d588d930.png)

## Additional context

The communication is good between the both side but i can't get the payload to connect my VM, i don't understand why.
Thank you for your help :)

**Comment by riskydissonance** [comment]
Hey, thanks for the detailed report!

Is there anything in the webserver.log for PoshC2 (in the project directory)?
Are you also able to upload or show the apache access.log & error.log files?

**Comment by riskydissonance** [comment]
Ah no, I see the issue, the kill date is in the past so the implants won't beacon... try updating that with `set-killdate <date>` from the ImplantHandler (or just change it in the config and start a new project)

**Comment by b4b857f6ee** [comment]
xD, i didn't see it ahah.
It's work now! Thank you !
