### ISSUE TITLE
PoshC2 can it be used with Ngrok or Portmap?

### ISSUE THREAD

**Issue by martinssssssss** [nettitude/PoshC2#114]
Hello, do you know how can it be used with Ngrok or Portmap?

**Comment by riskydissonance** [comment]
I'm not familiar with either of these tools, what do they do?

**Comment by martinssssssss** [comment]
> I'm not familiar with either of these tools, what do they do?

They are free port forward network utilities

**Comment by b4b857f6ee** [comment]
I guess with SharpSocks who are already with Posh v6.0 ?

**Comment by martinssssssss** [comment]
> I guess with SharpSocks who are already with Posh v6.0 ?

me too, and how to work with SharpSocks?

**Comment by riskydissonance** [comment]
Hey, check out https://poshc2.readthedocs.io/en/latest/usage/sharpsocks.html?highlight=sharpsocks 

Thanks @b4b857f6ee

**Comment by martinssssssss** [comment]
> Hey, check out https://poshc2.readthedocs.io/en/latest/usage/sharpsocks.html?highlight=sharpsocks
> 
> Thanks @b4b857f6ee
with SharpSocks you have to be already connected with the victim. The question is how set up the payloads to be connected not with your public IP when you traying to attack over wan. Can you use NGROK or Portmap insteаd your IP to set up payloads(in Posh-config)?
