### ISSUE TITLE
[BUG] - DaisyChain Payload download

### ISSUE THREAD

**Issue by b4b857f6ee** [nettitude/PoshC2#115]
## Description

The client cannot download the daisy payload passing throught the daisy host.
My fist infected workstation windows 10 is infected well. I configure the daisy host.
I can see in the webserver.log the second client passing through the daisyhost to download his payload but nothing, no download 404.

## Execution Environment:
**All of this must be filled in**
Kali update and VM
------ | ------
Full Posh version (all the text between the === at the top of the Implant Handler) | v6.0
OS & version | Ubuntu 18.04

## Implant Info
* What implant does the problem occur on? All
* How was the implant created? Running a default payload

## Defensive Technologies
* Nothing

## To Reproduce 
Infect one PC, start daisy host.
Create payload with the ip of the first implat and the port, create the associate firewall rules.
 Try to run the infected command from the generate payload to the other workstation who do not have internet access in the same subnet in my case.

## Expected behavior
Daisy payload download

## Screenshots
This is the request from the second client passing throught the first implat daisyhost: 
![image](https://user-images.githubusercontent.com/36012515/85399794-ad26ba00-b557-11ea-9aa7-0a6b0d0cca4b.png)

**Comment by b4b857f6ee** [comment]
I download the payload manually and execute on the second client and it's work, so this not a problem about the daisychain because it's work. By in the download process, where he can't find the payload to download it.
![image](https://user-images.githubusercontent.com/36012515/85402257-a8640500-b55b-11ea-96d6-fee6557c79a2.png)

I have also test with the psexecdaisychain  and it's work too. Maybe i miss something.

**Comment by riskydissonance** [comment]
Hey, how are you starting the daisy chaining? Are you using `startdaisy` or `createdaisypayload` ? 
Also, is it an elevated implant?

Thanks

**Comment by b4b857f6ee** [comment]
Hello :),
stardaisy and after they ask me to generate some payload.
I run the agent with the administrator account (yes not funny but for testing)

**Comment by riskydissonance** [comment]
You said *I can see in the webserver.log the second client passing through the daisyhost to download his payload but nothing, no download 404.* and *I download the payload manually and execute on the second client and it's work*, are you able to post the webserver.log entry for the latter case as well? Is it the same URL, UserAgent etc as the one that is 404ing?

**Comment by b4b857f6ee** [comment]
This is the webserver.log

![image](https://user-images.githubusercontent.com/36012515/85582846-0ec15400-b63e-11ea-92a8-efa157047441.png)

This is the command on the client 

![image](https://user-images.githubusercontent.com/36012515/85583063-387a7b00-b63e-11ea-90fe-9c60eb1a72d7.png)


And the payload generate after starting daisy
![image](https://user-images.githubusercontent.com/36012515/85583226-5cd65780-b63e-11ea-893a-2a096daa9f5a.png)

**Comment by riskydissonance** [comment]
Hey, so I've confirmed this locally, I'll investigate whether this is supposed to be supported or not or if it's an error with the daisy output and should be removed. Thanks for raising it!

**Comment by riskydissonance** [comment]
Hey so yeah the issue here is we don't support certutil downloads for Daisy implants, we'll remove this from the output to avoid confusion.

We do have stuff on the roadmap to allow general hosting of files however, so once that's done you'll be able to host things directly in PoshC2, in the meantime you'll have to manually move things over.

**Comment by b4b857f6ee** [comment]
Yeh, that's what a normal hacker will do for workstation without internet access ahah.

Thank you :)

**Comment by riskydissonance** [comment]
Hey, so this should be *partially* remedied now as we've added custom file hosting to PoshC2, but by default only the usual startup payloads are hosted.

For the above scenario you after generating Daisy payloads you then host them using `add-hosted-file`, the only caveat being that if you want to have Daisy payloads pick them up you have to host them at a URI which starts with the QuickCommandURI (this is printed in the server output when it starts). It'll then get routed down your Daisies to the C2 server and pick up your hosted payload.

We'll aim to make this more intuitive and document it after this coming release.

**Comment by b4b857f6ee** [comment]
thank you for your assit 👍
