### ISSUE TITLE
[FEATURE] Consider adding SharpCollection as an (GIT) submodule

### ISSUE THREAD

**Issue by Flangvik** [nettitude/PoshC2#127]
Consider adding https://github.com/Flangvik/SharpCollection as an submodule (git) to PoshC2?
SharpCollection automatically builds and pushes pre-compiled binaries for the latest C# offensive tools, aswell as provides a larger collection of them. Would greatly expand the existing C# toolkit already available in PoshC2 locally! Uses Azure DevOps for CDI, pipeline is public an 'open-source' https://dev.azure.com/FlangvikDev/SharpRelease/_build

**Comment by riskydissonance** [comment]
Hi Flangvik, 

Thanks for this! Unfortunately we don't want to automatically source third party modules as we want to maintain control over what's 'automatically' utilised by PoshC2. 
For example if PoshC2 was used on a red team engagement and someone pushed a malicious change to a third party tool that was automatically compiled and added and then run on that engagement then PoshC2 would be responsible for that.

We will however definitely check out some of the extra C# tools on the list! Thanks again!
