### ISSUE TITLE
[BUG] - Keystrokes nothing except mouse click

### ISSUE THREAD

**Issue by b4b857f6ee** [nettitude/PoshC2#166]
## Description

Cannot get keystrokes, only mouse.

## Execution Environment:
**All of this must be filled in**
Data | Value
------ | ------
Full Posh version (all the text between the === at the top of the Implant Handler) | 7.0
OS & version | OS Ubuntu 18.04
Using Docker/containerisation? | No

## Implant Info
* What implant does the problem occur on? PowerShell
* How was the implant created? Running a default payload? Powershell command

## Defensive Technologies
* Is the target environment running any particular defensive products? Outdated Windows Defender

## To Reproduce 
1. Go to poshc2
2. Infect the client
3. launch get-keystrokes
4. do some stuff on the infected client
5. launch get-keystrokedata
6. look at the posh return : nothing except mouse click

I'm using vmware console to interact with the VM.
Client infected : Windows 10 1703

## Expected behavior
See all keystrokes

## Screenshots
![image](https://user-images.githubusercontent.com/36012515/91417098-9307a180-e850-11ea-8092-4f224ca6e8de.png)

**Comment by benpturner** [comment]
Thanks for raising the issue. I’ll try and take a look shortly

**Comment by benpturner** [comment]
![image](https://user-images.githubusercontent.com/2518196/96004301-21e97100-0e33-11eb-9d74-5b2f16d70431.png)

**Comment by benpturner** [comment]
Seems to work on both C# and PS for me - closing this issue
