### ISSUE TITLE
[BUG] Python based implants fail to format Host Headers when multiple C2 Proxy Servers are used

### ISSUE THREAD

**Issue by galoryber** [nettitude/PoshC2#223]
## Description

Python based implants do not seem to properly format the Host header in HTTP requests when multiple domains are being used. 

## Execution Environment:
Full Posh version  | PoshC2 v7.3.0 (2c06985 2021-01-12 17:00:37)
OS & version | Ubuntu 20.04.1 LTS
Using Docker/containerization? | No

## Implant Info
* What implant does the problem occur on? 
Python
* How was the implant created? 
py_dropper.py - Default payload

## Defensive Technologies
* Is the target environment running any particular defensive products? AVs/EDRs etc?
Disabled all for testing

## To Reproduce 
1. Standard PoshC2 server is setup. Two PayloadCommsHost values are entered for two domains that will be used. Domain Fronting is not used, so the array is populated with ","
2. Two Apache C2 Proxy Servers are configured, one for each PayloadCommsHost domain. The standard PoshC2 documentation on Apache C2 Proxy setup was used. 
3. Windows based implants connect successfully, and as expected to either domain depending on availability. 
4. Python based implants fail to connect. Upon inspection, the initial python GET request can be seen sending a Host header with the value ['', '']. I used burp to intercept the request via proxychains python2 py_dropper.py. 
5. Manually changing the Host header to the correct domain allows the python based implant to check in, but subsequent requests follow the same behavior, showing an improperly formatted Host header. 

Python based implants do not seem to properly format the Host header in HTTP requests when multiple domains are being used. 

## Expected behavior
Python implants should mimic powershell or C# based implants in their connection attempts to allow for multiple domains, automatically selecting the first available domain for communications.

## Screenshots
![image](https://user-images.githubusercontent.com/51980089/106205996-022d4d00-6185-11eb-9cae-ad44537ff486.png)

## Additional context

In order to get the implants to properly communicate through the proxy, I had to include the following in the conf files for the virtual hosts. Without it, implants would check-in but fail to properly "upload" data. 
`<IfModule mod_headers.c>
RequestHeader unset Expect early
</IfModule>`

**Comment by benpturner** [comment]
Thanks for raising the bug - will look at getting this fixed

**Comment by benpturner** [comment]
![image](https://user-images.githubusercontent.com/2518196/109291793-5299d800-7821-11eb-9a01-9abdd8a009b6.png)

Its this line in the dropper - will push a change shortly. It should be taking the first one out of the array, e.g. hh[0]

**Comment by benpturner** [comment]
https://github.com/nettitude/PoshC2/pull/233

**Comment by galoryber** [comment]
Same change is needed in the Implant-Core.py otherwise the Implant will connect but lack functionality. Thanks!

**Comment by benpturner** [comment]
This should be DEV later this week after PR is approved.
