### ISSUE TITLE
[BUG] - database is locked

### ISSUE THREAD

**Issue by b4b857f6ee** [nettitude/PoshC2#234]
## Description

My last comment here : https://github.com/nettitude/PoshC2/issues/93

Hello, i got this error in PoshC2 2.7 on Ubuntu 18.04
I forget the infection in my attack scenario and i just saw more than 200 implant.... but th databse was saying it's lock...
How can i close all of this in the sqlite so i can start the poschC2 without rebuild all the payload etc :(...?
I have error like this : 
![image](https://user-images.githubusercontent.com/36012515/109339399-e42c3880-7867-11eb-96d2-145982fa018c.png)
Or this 
![image](https://user-images.githubusercontent.com/36012515/109339633-32d9d280-7868-11eb-97b4-a2301d8c8525.png)

![image](https://user-images.githubusercontent.com/36012515/109340415-48033100-7869-11eb-8ded-69c4400f5b21.png)

## Execution Environment:
**All of this must be filled in**
Data | Value
------ | ------
Full Posh version (all the text between the === at the top of the Implant Handler) | 2.7
OS & version | Ubuntu 18.04
Using Docker/containerisation? | no

## Implant Info
* What implant does the problem occur on? PowerShell
* How was the implant created? Running a default payload? default

## Defensive Technologies
* Is the target environment running any particular defensive products? AVs/EDRs etc?
* No

## To Reproduce 
Let my implant run again and again so you get many infection like 100

## Expected behavior
C2 working

## Screenshots
I have error like this : 
![image](https://user-images.githubusercontent.com/36012515/109339399-e42c3880-7867-11eb-96d2-145982fa018c.png)
Or this 
![image](https://user-images.githubusercontent.com/36012515/109339633-32d9d280-7868-11eb-97b4-a2301d8c8525.png)

![image](https://user-images.githubusercontent.com/36012515/109340415-48033100-7869-11eb-8ded-69c4400f5b21.png)

**Comment by riskydissonance** [comment]
Should just be a case of restarting the server/service & implant handler

**Comment by b4b857f6ee** [comment]
> 
> 
> Should just be a case of restarting the server/service & implant handler

Hello,
Thank you for your answer.
I already restart all... serveur too :(

**Comment by b4b857f6ee** [comment]
ok after removing some implant, create a new project and use the old projet, i was able to start it and remove all the implant :)
