### ISSUE TITLE
[BUG] Python3 Implant Not Working

### ISSUE THREAD

**Issue by r00t0v3rr1d3** [nettitude/PoshC2#248]
## Description

Using Python 3.9.2 that is installed by default on the latest up-to-date Kali results in errors and implants not functioning.

## Execution Environment:
**All of this must be filled in**
Data | Value
------ | ------
Full Posh version (all the text between the === at the top of the Implant Handler) | PoshC2 v7.4.0 (f6664b1)
OS & version | Kali 2021.2 Rolling
Using Docker/containerisation? | no

## Implant Info
* What implant does the problem occur on? Python
* How was the implant created? python3 /var/poshc2/project/py_dropper.py

## Defensive Technologies
* Is the target environment running any particular defensive products? No

## To Reproduce 
1. Install PoshC2 with defaults.
2. Create a project named project.
3. Run python3 /var/poshc2/project/py_dropper.py

## Expected behavior
Implant shows up as expected - "New Python implant connected..." - and it displays all the expected information, but it doesn't accept commands or return results. Every check-in it spits out:

error expected string or bytes-like object
'utf-8' codec can't decode byte byte 0xc1 in position 0: invalid start byte
error expected string or bytes-like-object

Also, when running the implant using python2, it appears to function properly, but every time it checks in with no tasking, it spits out an error: Incorrect padding.

## Screenshots
![poshc2_error1](https://user-images.githubusercontent.com/8229583/127713361-3ff33189-b755-4679-9552-b18d3e0245ac.png)
![poshc2_error2](https://user-images.githubusercontent.com/8229583/127713366-f4fa66e2-2d55-4006-b3e2-0382de5cc660.png)

**Comment by benpturner** [comment]
Hi,

Will give this a test shortly. Thanks for raising a bug, was the comms local e.g. over the local network or domain fronted or via a proxy or anything?

Thanks

**Comment by r00t0v3rr1d3** [comment]
The comms were local, on the same machine actually.

**Comment by benpturner** [comment]
Hi - do you mind trying this branch - https://github.com/nettitude/PoshC2/tree/update-mods

**Comment by benpturner** [comment]
<img width="826" alt="Screenshot 2021-08-08 at 17 06 20" src="https://user-images.githubusercontent.com/2518196/128638281-1d323497-2ae3-4d29-ada8-9c77114e0ceb.png">

**Comment by benpturner** [comment]
Tested against both python2 and python3. There are some errors on the dropper side that are not suppressed but are expected just FYI

**Comment by r00t0v3rr1d3** [comment]
Looks great! Python2 and Python3 implants working on latest Kali.

**Comment by benpturner** [comment]
Amazing, will get this PR closed and into DEV this week
