### ISSUE TITLE
[BUG] Install script makes reference to libicu63 but this is not available

### ISSUE THREAD

**Issue by yg-ht** [nettitude/PoshC2#251]
## Description

The installer tries to install libicu63 but this is not readily available in the current Ubuntu LTS / Kali repos.  There are some other dependency issues (around DotNet) but this is a good start.

## Execution Environment:

Posh commit ID | https://github.com/nettitude/PoshC2/commit/eb6dcb3d91af74982866cc877c41b9ce2074b00f (current master)
OS & version | Ubuntu 20.04 / Kali Latest

## To Reproduce 

Run the install script and inspect output

## Expected behavior

Dependencies correctly installed

## Possible fix

As the libicu versioning is package specific (rather than being versioned by APT), would it be sensible to change this to install libicu-dev?  If not, this could be changed to some form of case statement to ensure that whatever version is available is installed.

**Comment by benpturner** [comment]
Linked to - https://github.com/nettitude/PoshC2/issues/261
