### ISSUE TITLE
[BUG] - SharpSocks not currently working - libhostfxr.so could not be found

### ISSUE THREAD

**Issue by benpturner** [nettitude/PoshC2#260]
![image](https://user-images.githubusercontent.com/2518196/154041076-190d194c-05fc-49ff-8143-0bf4e2209c09.png)

**Comment by benpturner** [comment]
wget http://ftp.us.debian.org/debian/pool/main/i/icu/libicu57_57.1-6+deb9u4_amd64.deb
dpkg -i libicu57_57.1-6+deb9u4_amd64.deb
apt-get install -y dotnet-runtime-2.2
apt-get install -y dotnet-hostfxr-2.2 dotnet-host libssl1.1

**Comment by riskydissonance** [comment]
Fixed
