### ISSUE TITLE
[BUG] - Package 'libicu63' has no installation candidate

### ISSUE THREAD

**Issue by benpturner** [nettitude/PoshC2#261]
![image](https://user-images.githubusercontent.com/2518196/156766807-fdbeabe3-f8a8-483d-831b-dc741300c28b.png)

Current fix:

curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - >/dev/null
echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-debian-stretch-prod stretch main" > /etc/apt/sources.list.d/dotnetdev.list
apt-get update
wget http://ftp.us.debian.org/debian/pool/main/i/icu/libicu57_57.1-6+deb9u4_amd64.deb
dpkg -i libicu57_57.1-6+deb9u4_amd64.deb
apt-get install -y dotnet-runtime-2.2 dotnet-hostfxr-2.2 dotnet-host libssl1.1

**Comment by riskydissonance** [comment]
Fixed
