### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by captainkyd** [nettitude/PoshC2#284]
## Description

the installer script is broken at 'python -m pipenv --three install > /dev/null

## Execution Environment:
**All of this must be filled in**
Data | Value
------ | ------
whatever the latest version is, the installer updates 
OS & version | win 11 subsystem for linux

## To Reproduce 
1. simply run the Install.sh

## Expected behavior
I believe yall intended for a pipenv to be created. to make that work the '--three' must be removed as it is not recognized by the pipenv program. I imagine that the syntax was updated and the script was not.

## Screenshots
![Screenshot 2023-09-04 040022](https://github.com/nettitude/PoshC2/assets/25851329/bb033c1a-8845-401d-b683-f842c5340ee5)

**Comment by benpturner** [comment]
Thanks for rasing this.

**Comment by captainkyd** [comment]
my pleasure :-D
