### ISSUE TITLE
[FEATURE] Disable ETW and AMSI Patching in Implants

### ISSUE THREAD

**Issue by user1068** [nettitude/PoshC2#299]
## Is your feature request related to a problem? Please describe.

When I use the generated Implants with my custom loader, the Implants get caught because of the well know ETW and AMSI Patch patterns. My Loader does not use AMSI and ETW Patching, so I assume, it comes from the Implant. Is there a way to disable ETW and AMSI patching in the Implants?

**Comment by benpturner** [comment]
![image](https://github.com/user-attachments/assets/7f2edaa1-9c0c-4f4a-ae3e-582f8754ce19)

**Comment by benpturner** [comment]
You can turn those three features off with a hexeditor

**Comment by user1068** [comment]
Thank you for the quick response. This works, at least Windows 11 Defender does no complain about AMSI or ETW patching. Are there more "hidden" functionality like this? Would be nice to have this in the PoshC2 documentation. Or at least I have not seen this.

But, now I have another problem: Setting AMS=0 and ETW=0 broke some functionality:
![posh-error](https://github.com/user-attachments/assets/6abdcbe9-da4f-4539-861b-d6713b3cae90)

**Comment by benpturner** [comment]
Hi, some features have not made it through to our public release and we are in the process of publishing some of the new features in a blog article so watch this space, for example the native Windows payload which is created now. In your screenshot, Stage2-Core.exe has been caught by defender and this is why the core modules are not now working, it tells you in the screenshot you shared this was caught by AntiVirus. This can be evaded by simple AMSI bypass techniques

**Comment by user1068** [comment]
Another very useful hint :D Thanks. When I only disabled ETW and the Stage2-Core.exe gets loaded and the functionality works. Looking forward to read your blog!
