### ISSUE TITLE
C# implant is unable to download files in use

### ISSUE THREAD

**Issue by BaffledJimmy** [nettitude/PoshC2#36]
When using a C# implant, the operator is unable to download files that are in use by the target OS.

**Comment by riskydissonance** [comment]
Need to test if this is still the case/if this is possible to overcome

**Comment by Flangvik** [comment]
Take a look at https://github.com/GhostPack/LockLess, might solve the problem.

**Comment by riskydissonance** [comment]
Great shout, thanks @Flangvik ! PR created: https://github.com/nettitude/PoshC2/pull/143

**Comment by riskydissonance** [comment]
Closing issue, any further comments to go on the PR
