### ISSUE TITLE
'download-file' seems to lock files after completion

### ISSUE THREAD

**Issue by jmhickman** [nettitude/PoshC2#38]
Using 4.7, if I run `download-file` on a file, and then try to delete it from the remote host, I get a locking error from PowerShell

```
Command issued against implant 23 on host ALPHA 0METALAB (03/13/2019 05:56:36)
rm GUID.txt

Command returned against implant 23 on host 0METALAB\user @ ALPHA (03/13/2019 05:56:37)

rm : Cannot remove item C:\Users\user\GUID.txt: The process cannot access the file 'C:\Users\user\GUID.txt'
because it is being used by another process.
At line:1 char:1
+ rm GUID.txt
+ ~~~~~~~~~~~
    + CategoryInfo          : WriteError: (C:\Users\user\GUID.txt:FileInfo) [Remove-Item], IOException
    + FullyQualifiedErrorId : RemoveFileSystemItemIOError,Microsoft.PowerShell.Commands.RemoveItemCommand
```

Sometimes I can shake this off by running other PoshC2 commands, but not always.

**Comment by m0rv4i** [comment]
Hi @jmhickman, thanks for this one also, do you know if this is still the case on master?

The only thing that springs to mind is if the file is large it is downloaded in chunks, but GUID.txt sounds like a small file...?

**Comment by jmhickman** [comment]
And yeah, it was a small text file. File size doesn't seem to have any correlation to the issue. The only thing that seemed to remove the lock was to download another file, or sometimes to issue certain types of commands to the Implant, like changing directories. 

I'll have a look at master and let you know soon.

**Comment by jmhickman** [comment]
I can confirm that this is still the case on master, on Windows 10 Pro hosts running 1803. I tested on a Server 2008 system, and the problem didn't occur.

Windows 10 Pro host:

```
PS C:\Users\userguytwo> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.17134.590
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.590
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

Windows Server 2008 host:

```
Name                           Value
----                           -----
PSVersion                      3.0
WSManStackVersion              3.0
SerializationVersion           1.1.0.1
CLRVersion                     4.0.30319.42000
BuildVersion                   6.2.9200.22199
PSCompatibleVersions           {1.0, 2.0, 3.0}
PSRemotingProtocolVersion      2.2
```

**Comment by benpturner** [comment]
We’ve got plans to rework the download-file in both the C# implant and powershell implant so will check as part of this. Thanks for raising this though, assume its still an issue on master?

**Comment by jmhickman** [comment]
Not sure. My job has changed and I'm doing web app assessment for the time being, so my lab and my Posh install(s) have gotten out of date. Sorry. :(

**Comment by benpturner** [comment]
No worries at all, I think we narrowed down the problem and have pushed with this commit - https://github.com/nettitude/PoshC2/commit/690e9f9a5ffdd20d06db5181a1475291080a53d1
