### ISSUE TITLE
Flag which implants have Daisy running

### ISSUE THREAD

**Issue by phillips321** [nettitude/PoshC2#49]
Just like we have [SharpSocks] next to implants running the socks proxy any chance we can have [Daisy] next to implants running daisy? Makes remembering which implants are performing pivoting a little easier ;-)

**Comment by m0rv4i** [comment]
Hm that should already be the case 🤔 but it may be borked, I'll take a look, thanks!

**Comment by phillips321** [comment]
Implants that are connecting home through a daisy are flagged using the PS;D at the end of the line. But no way to tell which daisy they are using, or where daisy are running. Cheers Running 4.8

**Comment by benpturner** [comment]
This should now have a label - update_label("DaisyHost", randomuri)
