### ISSUE TITLE
Notify when end date is near/has passed

### ISSUE THREAD

**Issue by b1gdave** [nettitude/PoshC2#54]
When setting the end date of payloads in Posh there is no warning in the framework when the kill date has been set in the past (e.g. you're on an engagement and forget to edit the date and can't get anything to come back because you've not been paying attention). Is there any way a warning/error message could be shown to help with debugging?

**Comment by benpturner** [comment]
https://github.com/nettitude/PoshC2/commit/ac2cae4a8ff80a59943053762c969beea3f0d398
