### ISSUE TITLE
upload-file error in PS implant

### ISSUE THREAD

**Issue by ghost** [nettitude/PoshC2#63]
Exception calling "WriteAllBytes" with "2" argument(s): "Access to the path 'c:\users\public\videos' is denied."
At line:536 char:13
+             [io.file]::WriteAllBytes($Destination, $fileBytes)
+ CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
+ FullyQualifiedErrorId : UnauthorizedAccessException

The above error happens in PS implant, when you try to upload a file. However, within the same directory, one can create a new file with echo test > test.txt and when listed, it's there, in the same folder, which means you do have access to write to that path.

**Comment by ghost** [comment]
Also, when uploading to a non-existent path, seems like the upload was successful.

Uploading file: **c:\\users\\public\\video** with md5sum: 0ea598251188271e4a8e6501e9520798
**Uploaded file as HIDDEN & SYSTEM to: c:\\users\\public\\video**
Run Get-ChildItem -Force to view the uploaded files

**Comment by riskydissonance** [comment]
Hmm so for the latter I get an error if it doesn't exist

```
Task 00011 (R2B2) issued against implant 1 on host DESKTOP-J8RAGA9\Bob @ DESKTOP-J8RAGA9 (03/12/2019 20:51:02)
Uploading file: Upload-File -Destination "C with md5sum: 784112ac8618f1b98f1af24bcd1a43b8


Task 00011 (R2B2) returned against implant 1 on host DESKTOP-J8RAGA9\Bob @ DESKTOP-J8RAGA9 (03/12/2019 20:51:03)

Exception calling "WriteAllBytes" with "2" argument(s): "Could not find a part of the path
'C:\Users\doesnotexist\definitelydoesnotexist.exe'."
At line:536 char:13
+             [io.file]::WriteAllBytes($Destination, $fileBytes)
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : DirectoryNotFoundException
```

Is it not that you're uploading the file to C:\Users\Public, as a file called video? I believe you have to specify a full path including filename with `upload-file`.

In fact I think the same issue occurs for the first error - I think the reason it's denied is because it's trying to write the file to a file called Videos, which already exists as a directory?
