### ISSUE TITLE
After "loadmodule", run-exe doesn't work. 

### ISSUE THREAD

**Issue by edwardyeung** [nettitude/PoshC2#65]
PoshC2 version: 5.1
Linux: Ubuntu 18.04

I tried run-exe after "loadmodule", but it doesn't work.
Then I found a blog post (https://labs.nettitude.com/blog/introducing-poshc2-v5-0/).
Looks like it has been changed to <namespace> <args> or <class> <args>. I tried both and it still failed.
 
What is the command the run the module?

**Comment by riskydissonance** [comment]
Hi, the documentation is at https://poshc2.readthedocs.io/, with details on `run-exe` [here](https://poshc2.readthedocs.io/en/latest/extending/index.html).

If you still have issues just create new issue but please detail the Posh version, command being issued and binary being loaded!

Thanks
