### ISSUE TITLE
The term <run-exe> is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

### ISSUE THREAD

**Issue by edwardyeung** [nettitude/PoshC2#66]
PoshC2 Version: 5.1 - 21553fa 2019-12-07 
Loaded Module: SharpChrome.exe

Used Command:
loadmodule SharpChrome.exe  - Module loaded successfully
run-exe SharpChrome.Program SharpChrome logins - The term <run-exe> is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.

I tried other module ( SharPersist, seatbelt) and it gave me same result. ( it can't recognize run-exe )

**Comment by riskydissonance** [comment]
Hi Edward,

The run-exe command is for c# implants only, it looks like you’re running it in a PowerShell implant, is that correct?

Thanks

**Comment by edwardyeung** [comment]
> 
> Hi Edward, The run-exe command is for c# implants only, it looks like you’re running it in a PowerShell implant, is that correct? Thanks
> […](#)
> On 9 Dec 2019, at 18:13, Edward ***@***.***> wrote: ﻿ PoshC2 Version: 5.1 - [21553fa](https://github.com/nettitude/PoshC2/commit/21553fa8b24a3f8ced3d0f1aeca65eb8d61c2257) 2019-12-07 Loaded Module: SharpChrome.exe Used Command: loadmodule SharpChrome.exe - Module loaded successfully run-exe SharpChrome.Program SharpChrome logins - The term is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. I tried other module ( SharPersist, seatbelt) and it gave me same result. ( it can't recognize run-exe ) — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

Yes.
Sorry for my mistake.
