### ISSUE TITLE
Non-Standard Date Formatting Used

### ISSUE THREAD

**Issue by Console** [nettitude/PoshC2#67]
@benpturner

PoshC2 is an internationally used product, yet uses confusing UK date formatting for its output and configuration.

https://xkcd.com/1179/

The international organisation for standardisation (ISO) has a worldwide accepted format for date formatting defined as part of ISO 8601 - This follows the following formatting:

YYYY-MM-DD HH:MM:SS

This becomes easier to sort in tables, easier to read in output and results in no ambiguity from any users of PoshC2.

**Comment by riskydissonance** [comment]
You fancy doing this as a PR? Any issues can just ping me :)

**Comment by riskydissonance** [comment]
Done at https://github.com/nettitude/PoshC2/commit/a299b8a074a96ce01262682d79e7bc5cec53f85b
