### ISSUE TITLE
Download file issues

### ISSUE THREAD

**Issue by m-nadeem-ashraf** [nettitude/PoshC2#71]
When downloading any file types with slightly large size (few MBs) following error is thrown:

Error downloading file:
ErrorDownload: Exception calling "UploadData" with "2" argument(s): "The request was aborted: The request was canceled."
Unknown error!
Input strings must be a multiple of 16 in length
Traceback (most recent call last):
  File "C2Server.py", line 372, in do_POST
    rawoutput = decrypt_bytes_gzip(encKey, post_data[1500:])
  File "/opt/PoshC2/Core.py", line 69, in decrypt_bytes_gzip
    data = aes.decrypt(data)
  File "/root/.local/share/virtualenvs/PoshC2-KGSTtxLR/lib/python3.6/site-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
ValueError: Input strings must be a multiple of 16 in length

**Comment by benpturner** [comment]
Was this in the C# implant or the PS implant?

**Comment by m-nadeem-ashraf** [comment]
PS implant

**Comment by benpturner** [comment]
Do you have any files that seem to generate this error? I’ve tried downloading a few exes with various sizes and they seem to work ok

**Comment by riskydissonance** [comment]
Hey, this has been reworked and a few bugs fixed. I'll close this for now but please re-open it if the issue resurfaces!

The only other thing that may cause something like this is if the connection is flakey and the stream is dropped, meaning the not all the data makes it and therefore cannot be encrypted.
