### ISSUE TITLE
Documentation missing sudo requirements

### ISSUE THREAD

**Issue by m3ldis** [nettitude/PoshC2#77]
Running `posh-service` or `posh-server` without sudo doesn't work on Ubuntu 18, having something to do with "polkit" Authorization Manager not allowing systemctl calls. But once you accidentally run it without sudo it gets stuck because the prompt won't exit properly with Ctrl+C out of the polkit prompt (it puts all prompts on the same line and won't show typing). 

The Auth Manager thing isn't PoshC2's problem but it could be avoided by telling users to run all commands with sudo or from a root prompt.

**Comment by riskydissonance** [comment]
Thanks @clhefton, I've updated the README to detail that if you want to use a privileged port (such as 443) then you need to run from an elevated prompt.
