### ISSUE TITLE
posh-server complains about "Crypto" python lib

### ISSUE THREAD

**Issue by bigdavros** [nettitude/PoshC2#80]
I had an error where PoshC2 server was complaining about no "Crypto" library when implants were coming in on PoshC2 v5.2. It was causing implants to fail.

For a temp fix I found running:
`python3 -m pipenv run pip uninstall pycrypto`
Then:
`python3 -m pipenv run pip install pycryptodome`

Did the trick.

**Comment by riskydissonance** [comment]
Hi b1gdave, thanks for this! What OS are you installing it on and are you running it via docker?

Thanks

**Comment by bigdavros** [comment]
Hi m0rv4i

I was running it on a fresh install of: Linux hostname 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux

It was on a VM rather than in Docker.

**Comment by riskydissonance** [comment]
This should be fixed as now moved to Kali as base image, if you encounter it again let us know :)
