### ISSUE TITLE
Report Generation Not Working

### ISSUE THREAD

**Issue by InitRoot** [nettitude/PoshC2#84]
Running on Ubuntu 16.04 with Python 3.8.

Everything works okay, but when I try to generate a report I get the following error:

`Error:` module 'cgi' has no attribute 'escape'

**Comment by riskydissonance** [comment]
Hi InitRoot,

Thanks for the issue, can you try commenting this line and trying again? You'll have to restart the implant handler after making the code change.

https://github.com/nettitude/PoshC2/blob/master/poshc2/client/reporting/HTML.py#L395

**Comment by InitRoot** [comment]
Thanks, that doesn't seem to fix the issue. However I could fix it by doing the following:

`import html 
`
Change the following lines 402 and 403:
```
            frame.loc[index, "Command"] = replace_tabs(cgi.escape(row["Command"]))
            frame.loc[index, "Output"] = replace_tabs(cgi.escape(row["Output"]))
```




To the following:
```
            frame.loc[index, "Command"] = replace_tabs(html.escape(row["Command"]))
            frame.loc[index, "Output"] = replace_tabs(html.escape(row["Output"]))
```

**Comment by InitRoot** [comment]
Just thinking can we commit this  to update? Believe that the cgi in the new python isn't the way to reference escape anymore.

**Comment by riskydissonance** [comment]
Done, thanks
