### ISSUE TITLE
Posh-service not finding Yaml module

### ISSUE THREAD

**Issue by nickkilla** [nettitude/PoshC2#86]
Yaml is installed and I also installed via pipenv yet no joy on the service setup seeing it. I have added to bash profile the directory it shows installed
nickkilla@box:~$ uname -a
Linux box 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
nickkilla@box:~$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
'nickkilla@box:~$ sudo pip3 install pyyaml
WARNING: The directory '/home/nickkilla/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Requirement already satisfied: pyyaml in /usr/lib/python3/dist-packages (3.12)
nickkilla@box:~$ sudo python3 -m pipenv run pip install pyyaml
Creating a virtualenv for this project…
Pipfile: /home/nickkilla/Pipfile
Using /usr/bin/python3 (3.6.9) to create virtualenv…
⠇ Creating virtual environment...created virtual environment CPython3.6.9.final.0-64 in 504ms
  creator CPython3Posix(dest=/home/nickkilla/.local/share/virtualenvs/nickkilla-vAbj4hxZ, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/home/nickkilla/.local/share/virtualenv/seed-v1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment! 
Virtualenv location: /home/nickkilla/.local/share/virtualenvs/nickkilla-vAbj4hxZ
Creating a Pipfile for this project…
WARNING: The directory '/home/nickkilla/.cache/pip' or its parent directory is not owned or is not writable by the current user. The cache has been disabled. Check the permissions and owner of that directory. If executing pip with sudo, you may want sudo's -H flag.
Collecting pyyaml
  Downloading PyYAML-5.3.tar.gz (268 kB)
     |████████████████████████████████| 268 kB 16.1 MB/s 
Building wheels for collected packages: pyyaml
  Building wheel for pyyaml (setup.py) ... done
  Created wheel for pyyaml: filename=PyYAML-5.3-cp36-cp36m-linux_x86_64.whl size=44229 sha256=30d9ed31d412870b00f0096e8366b9893bfc1ef8ac12907a63ef322141927f6c
  Stored in directory: /tmp/pip-ephem-wheel-cache-j6rg_hts/wheels/b1/86/0d/10e6c39d3a2b85ba807d7657ee80f08cc16c03f2aa2adf8e46
Successfully built pyyaml
Installing collected packages: pyyaml
Successfully installed pyyaml-5.3
nickkilla@box:~$ sudo posh-service
Creating a virtualenv for this project…
Pipfile: /opt/PoshC2/Pipfile
Using /usr/bin/python3.8 (3.8.0) to create virtualenv…
⠏ Creating virtual environment...created virtual environment CPython3.8.0.final.0-64 in 594ms
  creator CPython3Posix(dest=/root/.local/share/virtualenvs/PoshC2-KGSTtxLR, clear=False, global=False)
  seeder FromAppData(download=False, pip=latest, setuptools=latest, wheel=latest, via=copy, app_data_dir=/root/.local/share/virtualenv/seed-v1)
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator

✔ Successfully created virtual environment! 
Virtualenv location: /root/.local/share/virtualenvs/PoshC2-KGSTtxLR
Traceback (most recent call last):
  File "start.py", line 8, in <module>
    run()
  File "/opt/PoshC2/poshc2/__init__.py", line 13, in run
    server.start()
  File "/opt/PoshC2/poshc2/server/__init__.py", line 6, in start
    from poshc2.server.C2Server import main
  File "/opt/PoshC2/poshc2/server/C2Server.py", line 7, in <module>
    from poshc2.server.Implant import Implant
  File "/opt/PoshC2/poshc2/server/Implant.py", line 3, in <module>
    from poshc2.server.Config import PayloadsDirectory, PayloadTemplatesDirectory, Jitter, ClockworkSMS_APIKEY, Pushover_APIToken, Pushover_APIUser, Sounds, ClockworkSMS_MobileNumbers, NotificationsProjectName
  File "/opt/PoshC2/poshc2/server/Config.py", line 1, in <module>
    import os, yaml
ModuleNotFoundError: No module named 'yaml'
Traceback (most recent call last):
  File "start.py", line 8, in <module>
    run()
  File "/opt/PoshC2/poshc2/__init__.py", line 13, in run
    server.start()
  File "/opt/PoshC2/poshc2/server/__init__.py", line 6, in start
    from poshc2.server.C2Server import main
  File "/opt/PoshC2/poshc2/server/C2Server.py", line 7, in <module>
    from poshc2.server.Implant import Implant
  File "/opt/PoshC2/poshc2/server/Implant.py", line 3, in <module>
    from poshc2.server.Config import PayloadsDirectory, PayloadTemplatesDirectory, Jitter, ClockworkSMS_APIKEY, Pushover_APIToken, Pushover_APIUser, Sounds, ClockworkSMS_MobileNumbers, NotificationsProjectName
  File "/opt/PoshC2/poshc2/server/Config.py", line 1, in <module>
    import os, yaml
ModuleNotFoundError: No module named 'yaml'
Traceback (most recent call last):
  File "start.py", line 8, in <module>
    run()
  File "/opt/PoshC2/poshc2/__init__.py", line 13, in run
    server.start()
  File "/opt/PoshC2/poshc2/server/__init__.py", line 6, in start
    from poshc2.server.C2Server import main
  File "/opt/PoshC2/poshc2/server/C2Server.py", line 7, in <module>
    from poshc2.server.Implant import Implant
  File "/opt/PoshC2/poshc2/server/Implant.py", line 3, in <module>
    from poshc2.server.Config import PayloadsDirectory, PayloadTemplatesDirectory, Jitter, ClockworkSMS_APIKEY, Pushover_APIToken, Pushover_APIUser, Sounds, ClockworkSMS_MobileNumbers, NotificationsProjectName
  File "/opt/PoshC2/poshc2/server/Config.py", line 1, in <module>
    import os, yaml
ModuleNotFoundError: No module named 'yaml'
Traceback (most recent call last):
  File "start.py", line 8, in <module>
    run()
  File "/opt/PoshC2/poshc2/__init__.py", line 13, in run
    server.start()
  File "/opt/PoshC2/poshc2/server/__init__.py", line 6, in start
    from poshc2.server.C2Server import main
  File "/opt/PoshC2/poshc2/server/C2Server.py", line 7, in <module>
    from poshc2.server.Implant import Implant
  File "/opt/PoshC2/poshc2/server/Implant.py", line 3, in <module>
    from poshc2.server.Config import PayloadsDirectory, PayloadTemplatesDirectory, Jitter, ClockworkSMS_APIKEY, Pushover_APIToken, Pushover_APIUser, Sounds, ClockworkSMS_MobileNumbers, NotificationsProjectName
  File "/opt/PoshC2/poshc2/server/Config.py", line 1, in <module>
    import os, yaml
ModuleNotFoundError: No module named 'yaml'`

**Comment by nickkilla** [comment]
Saw same issue in closed, will try solution there.

**Comment by nickkilla** [comment]
nickkilla@box:~$ sudo posh
Traceback (most recent call last):
  File "start.py", line 8, in <module>
    run()
  File "/opt/PoshC2/poshc2/__init__.py", line 10, in run
    client.start()
  File "/opt/PoshC2/poshc2/client/__init__.py", line 5, in start
    from poshc2.client.command_handlers.ImplantHandler import main
  File "/opt/PoshC2/poshc2/client/command_handlers/ImplantHandler.py", line 5, in <module>
    from poshc2.server.DB import update_item, get_c2server_all, get_implants_all, get_tasks, get_implantdetails, new_urldetails
  File "/opt/PoshC2/poshc2/server/DB.py", line 4, in <module>
    from poshc2.server.Config import Database
  File "/opt/PoshC2/poshc2/server/Config.py", line 1, in <module>
    import os, yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by nickkilla** [comment]
So tried the steps in the other Yaml closed issue. I did the pip install requirements and redid the ./Install and still shows no yaml when trying to run posh lister

**Comment by nickkilla** [comment]
Not sure if this is the issue

Package libicu63 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libicu63' has no installation candidate

**Comment by m3ldis** [comment]
I had the same issue (I didn't see the libicu63 problem). After running `python3 -m pip install --force-reinstall -r requirements.txt` it showed that PyYAML had been installed by distutils and couldn't be installed by pip. So I did `apt remove PyYAML`, re-ran the pip command, and updated posh. It worked for me. I am using the docker install. 

Warning, if you see this in the next few hours, see my other issue regarding the kali docker build.

Edit: there's probably a better way to do this, i.e., tell pip or pipenv or whatever to use the system PyYAML, but this was the quickest fix.

**Comment by riskydissonance** [comment]
Thanks @clhefton. @nickkilla  are you able to confirm if this fixed the issue?

Unfortunately we can't account for what's installed on the OS and if it clashes. You can try docker if it still doesn't work.

**Comment by m3ldis** [comment]
@m0rv4i this issue happens with the docker installation. I don't know about the normal one. I just re-tried the fix I mentioned and I'm not sure how it happened the first time, but it didn't work this time. 

Different fix.

@nickkilla I did actually notice the libicu63 error but it doesn't affect anything. The root issue is actually with pipenv somehow not calling the right python, even though I only have one on my system. Maybe it was using some random version within the docker build and that version can't find anything installed with pip? 

To get it to work, in /usr/bin/posh-server, change the following:

```
    python3 -m pipenv run python3 -u start.py --server 2>&1 | tee -a "$POSH_PROJECT_DIR/poshc2_server.log"
```
to:
```
    python3 -m /usr/bin/pipenv run python3 -u start.py --server 2>&1 | tee -a "$POSH_PROJECT_DIR/poshc2_server.log"
```

**Comment by nickkilla** [comment]
@clhefton The solution yesterday solved the issue.

**Comment by yg-ht** [comment]
I have hitting my head against this issue and trying to work through it and suddenly realised that I was running Install.sh as non-priv user with sudo...  This sets up a Virtualenv for the low-priv user which means when you come to run the service as root it can't find the libraries.

It might be a good idea to stick a flag in Install.sh for "don't use sudo" or to change the venv creation process to cope.  Off the top of my head though, I don't know how to do this...

(edited for grammar)

**Comment by riskydissonance** [comment]
I agree I think I need to investigate the sudo/pipenv behaviour, will add that to the shortlist

**Comment by riskydissonance** [comment]
@yg-ht i'm actually confused a little by your last comment, as if you're using a none-priv user and sudo to install the script then are you *not* using that same low privileged user to run PoshC2 (using sudo again)? If so it should be using the same environment. Either way it would be recommended to use the same technique for installing and running PoshC2.

Having done some testing across OSs and users, my observations are:
* Running install as sudo creates the virtual environment under /root
* Running `posh-` commands using sudo uses the same virtualenv and it works
* Running the `posh-` commands without sudo or as a different user doesn't work, as the virtual env is not set up for that user
![image](https://user-images.githubusercontent.com/20513519/80952124-12c8b680-8df1-11ea-9141-34d12a0d1b4d.png)

Is that inline with what you're seeing?

**Comment by yg-ht** [comment]
Thanks for having a look.  I think the difference lies with the fact
that I didn't curl and then pipe to bash.  I had the repo cloned locally
and then "sudo ./Install.sh" which does not maintain the privs for the
creation of the virtual env.  I believe the reason yours works is
because you elevate the shell and then give it things to do, whilst my
method elevates the script and not necessarily the actions it calls. 
Hope that clarifies it.

**Comment by ramoncjs3** [comment]
Because postgresql is supported in the configuration, and postgresql is not installed in Kali, an error is reported during the automatic installation process because psycopg2 is not installed successfully.
The solution is as follows:
apt-get install postgresql
apt-get install python-psycopg2
apt-get install libpq-dev
python3 -m pip install --force-reinstall -r requirements.txt

**Comment by riskydissonance** [comment]
:+1:  thanks ramoncjs3
