### ISSUE TITLE
Cant run any custom/external modules

### ISSUE THREAD

**Issue by shadyhamsters** [nettitude/PoshC2#87]
On a Powershell Implant, ive tried typing in:
Running Poshc2 5.2 via Launcher.hta

LoadModule Invoke-MS16-032.ps1
LoadModule PPID-Spoof.ps1

But when i try invoke these methods, it says cmdlet not recognized. What could be the problem here?

**Comment by riskydissonance** [comment]
Hi @shadyhamsters it could be getting caught by AMSI, are you able to paste text or a screenshot of the commands and their output?

**Comment by riskydissonance** [comment]
Closing dead issue.
