### ISSUE TITLE
The latest docker commit uses the wrong Kali Docker file

### ISSUE THREAD

**Issue by m3ldis** [nettitude/PoshC2#89]
Unfortunately, I just did a fresh reinstall of posh after removing everything for other issues literally an hour ago, right after your recent change to the dockerfile, and now it won't install for docker. 

```
Step 1/6 : FROM kalilinux/kali-linux-docker
pull access denied for kalilinux/kali-linux-docker, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

Furthermore, it says on their site at https://www.kali.org/docs/containers/official-kalilinux-docker-images/ 
**"Please note, kalilinux/kali-linux-docker is the former official image, it’s no longer updated. Don’t use it."**

**Comment by m3ldis** [comment]
installing using the supported Kali image (`kalilinux/kali-rolling`) by changing the Dockerfile "FROM" line, then re-running `posh-docker-build`, resulted in a successful install.

**Comment by riskydissonance** [comment]
Nice catch, thanks.

Interestingly the kalilinux/kali-linux-docker 'works for me' however as you mention it's no longer the official image so it's been updated.
