### ISSUE TITLE
Python command in py_dropper.sh should be changed

### ISSUE THREAD

**Issue by m3ldis** [nettitude/PoshC2#90]
Feel free to close if you disagree, but I suggest `| python` be changed to `| python2.7` by default in dropper.sh. 

On most new machines, including the mac's I've owned and on some Ubuntu machines, only Python3 comes installed. Sometimes the only existing python commands are `python3` and `python3<.x>`, and sometimes even `python` also points to Python 3. On any system with Python 2.7 installed, the command `python2.7` WILL exist. Even if `python` exists and points to a Python 2 version, it will only be a symlink to `/usr/bin/python2.7`. 

Since this is the required version, it would make more sense IMO to explicitly specify this to avoid the `urllib2` error you get from trying to run the .sh with Python 3.

Also, minor feature request: make a separate Python 2.6-compatible payload (the only thing you have to change is removing the `ssl._create_unverified_context` line, since ssl in 2.6 doesn't have that feature). On older linux systems I have to base64 decode the .sh contents, remove that line, and manually run the resulting .py file.

**Comment by riskydissonance** [comment]
Good shout, change pushed on dev: https://github.com/nettitude/PoshC2/commit/cbab8cc0e8f9386a2ed716f47eb3d2ee74c63d4e
