### ISSUE TITLE
Redirector issue?

### ISSUE THREAD

**Issue by Neilhoman** [nettitude/PoshC2#92]
Hey thank you for such an amazing product much appreciate your hard work building and sharing such tool. 

I'm playing with PoshC2 and my question is around redirector setup. I followed proxy redirector setup here https://labs.nettitude.com/tools/poshc2/poshc2-documentation/.  How do i go about specify the redirector URL or IP in the and regenerate payloads? at the C2 level i can only see Hostname and Domain Front Header variables i can’t see redirector variable to so that i can regenerate payloads at the moment all traffic hits the direct c2 server and i want to ensure when the payload executed first to hit the redirector then rewrite to the c2 server. Much appreciate if you can clarify that?  I'm new to all that :) 

HostnameIP: 
DomainFrontHeader:

**Comment by Neilhoman** [comment]
Resolved - My bad for not following the instructions. Thanks!

**Comment by riskydissonance** [comment]
Sorry Neil totally missed this one but glad you solved it!
